### ISSUE TITLE
Apply Patch: timed loop and iteration.

### ISSUE THREAD

**Issue by lumy** [lumy/EternityII#29]
Check the patch, run it, push it. (cleanly)
Two patch, one with \r\n another with \'n only.

**Also this patch contain would resolv #28 issue.**

[timed_puzzle.zip](https://github.com/lumy/EternityII/files/752349/timed_puzzle.zip)

Use by setting True or False in the main.py. line 104.

**Comment by Grenadingue** [comment]
@lumy why didn't you pushed it on some git branches ?

**Comment by lumy** [comment]
@Grenadingue I was on the master when i did that, instead of pushing it i juste got an patch of it. next step do a real branch so we can apply the patch

**Comment by Grenadingue** [comment]
next time please don't submit files changes via zipped diffs
