### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Grenadingue** [lumy/EternityII#37]
Update `README.md` for the current implementation

It should contains:

- The installation process (pip install -r requirements.txt)
- Explanation about the config,py (the minimal required)
- Explanation about how to render.
- Some links to our documentation (Idees V1, IdeesV2, Implementations...).

**Comment by lumy** [comment]
Workflow type:

    $ main.py
    personal_path is <personal_path>
    [...]
    $ render.py <personal_path>
    [...]
    $ script bash

**Comment by Grenadingue** [comment]
I would have added `$ algo_benchmark.py` too

**Comment by lumy** [comment]
Please have a new review. (still will be missing explanation of configuration. Will be done later).

EDIT: Sorry wrong place, i was talking about the PR.
