### ISSUE TITLE
New error while Executing. called of ord() with a string of len 0

### ISSUE THREAD

**Issue by lumy** [lumy/EternityII#47]
During the exec of the main this message appear:

    ord() expected a character, but string of length 0 found

It shouldn't where does it come from ? is that produce a big error or is that in a try/catch and doesn't matter ?

**Comment by AdriVig** [comment]
I don't have this error, can you provide more explanation like your config.py file and the command line you typed please ?

**Comment by lumy** [comment]
getting that on the main.py with the config on master.

**Comment by Grenadingue** [comment]
I just tested right now on Linux, on `master`, with default `config.py` and I don't have this error

**Comment by lumy** [comment]
i'll investigate on that it's surely my windows that is failing somewhere.
