### ISSUE TITLE
Puzzle Completion V3

### ISSUE THREAD

**Issue by lumy** [lumy/EternityII#51]
La valeur `puzzle_completion` représente actuellement le pourcentage de bonnes connexions valides par individu `[0; 4]`, et ce pour la totalité du plateau `[0; 4] * n`
La valeur `puzzle_completion` ne représente pas la complétion réelle du puzzle, en terme de nombre de pièces que l’on considère comme “bien posées”, valides
Il faudrait remplacer le nom de l’ancienne valeur `puzzle_completion` par `connections_completion`
Il faudrait pour la variable `puzzle_completion`:
Compter le nombre d’individus dont le score individuel est à 4
Calculer le pourcentage réel de complétion du puzzle `nb_valid_ind / nb_total_ind`

**Comment by Grenadingue** [comment]
In `puzzle.py`, `eval.eval_solution(self.population)` now returns
```python
individuals_s, individuals_clusters_s, puzzle_completion, connections_completion, nb_individuals_per_ind_score
```
- `puzzle_completion` is the real puzzle completion score `nb_valid_ind * 100 / nb_total_ind`
- `connections_completion` is `sum(individuals_score) * 100 / nb_total_connections`
- `nb_individuals_per_ind_score` is a list which count the number of individuals to a given score
  - at index `0` of the list we have the number of individuals with a score of `0`
  - at index `1` of the list we have the number of individuals with a score of `1`
  - etc
