### ISSUE TITLE
more of a question than a bug

### ISSUE THREAD

**Issue by ghost** [lumy/EternityII#70]
Hi! Quoted from your readme: "The e2pieces.txt file contains the pieces per line with direction ordered as (n, s, w, e). For convienience we order them as (n, e, s, w)." Does this mean that your e2pieces.txt list orders the tile pieces as (n, s, w, e) or (n, e, s, w)? Thanks!

**Comment by lumy** [comment]
Hello,

I'll get the time to make it more clear.

The file is ordered as (n, s, w, e) and we don't change it. like that (so
that's the same order than images, and we can easily apply the rotation.
When we initialize a Ind (a Piece in ind.py) we reorder them. (
https://github.com/lumy/EternityII/blob/master/ind.py#L48)

Your Welcome

Timothee MENAGE - Lumy
+336 95 53 76 88

lumy@protonmail.com
lumy@lumy.me



2018-06-21 4:27 GMT+02:00 SuperSynth <notifications@github.com>:

**Comment by ghost** [comment]
Thank you so much! :) So in e2pieces.txt, for example the line "1 0 0 17" indicates that the north section/triangle of that piece is color 1, the south is gray/0, the west is gray/0, and the east section is color 17?

**Comment by lumy** [comment]
Yep that's it.

**Comment by ghost** [comment]
Awesome! And for example "3 2 3 7" means that the north segment is color 3, the south is color 2, the west is color 3, and the east is color 7? Thank you very much for your help! Your software program is great!

**Comment by lumy** [comment]
Yep

Timothee MENAGE - Lumy
+336 95 53 76 88

lumy@protonmail.com
lumy@lumy.me



2018-06-21 16:13 GMT+02:00 SuperSynth <notifications@github.com>:

**Comment by ghost** [comment]
Thanks! Have a great day!
